/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AnomaliesRouteImport } from './routes/anomalies'
import { Route as LiveMonitoringRouteImport } from './routes/live-monitoring'
import { Route as NetworkMapRouteImport } from './routes/network-map'
import { Route as SensorHealthRouteImport } from './routes/sensor-health'
import { Route as StationsRouteImport } from './routes/stations'
import { Route as SystemIntelligenceRouteImport } from './routes/system-intelligence'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AnomaliesRoute = AnomaliesRouteImport.update({
  id: '/anomalies',
  path: '/anomalies',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveMonitoringRoute = LiveMonitoringRouteImport.update({
  id: '/live-monitoring',
  path: '/live-monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkMapRoute = NetworkMapRouteImport.update({
  id: '/network-map',
  path: '/network-map',
  getParentRoute: () => rootRouteImport,
} as any)
const SensorHealthRoute = SensorHealthRouteImport.update({
  id: '/sensor-health',
  path: '/sensor-health',
  getParentRoute: () => rootRouteImport,
} as any)
const StationsRoute = StationsRouteImport.update({
  id: '/stations',
  path: '/stations',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemIntelligenceRoute = SystemIntelligenceRouteImport.update({
  id: '/system-intelligence',
  path: '/system-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/anomalies': typeof AnomaliesRoute
  '/live-monitoring': typeof LiveMonitoringRoute
  '/network-map': typeof NetworkMapRoute
  '/sensor-health': typeof SensorHealthRoute
  '/stations': typeof StationsRoute
  '/system-intelligence': typeof SystemIntelligenceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/anomalies': typeof AnomaliesRoute
  '/live-monitoring': typeof LiveMonitoringRoute
  '/network-map': typeof NetworkMapRoute
  '/sensor-health': typeof SensorHealthRoute
  '/stations': typeof StationsRoute
  '/system-intelligence': typeof SystemIntelligenceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/anomalies': typeof AnomaliesRoute
  '/live-monitoring': typeof LiveMonitoringRoute
  '/network-map': typeof NetworkMapRoute
  '/sensor-health': typeof SensorHealthRoute
  '/stations': typeof StationsRoute
  '/system-intelligence': typeof SystemIntelligenceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/anomalies'
    | '/live-monitoring'
    | '/network-map'
    | '/sensor-health'
    | '/stations'
    | '/system-intelligence'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/anomalies'
    | '/live-monitoring'
    | '/network-map'
    | '/sensor-health'
    | '/stations'
    | '/system-intelligence'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/anomalies'
    | '/live-monitoring'
    | '/network-map'
    | '/sensor-health'
    | '/stations'
    | '/system-intelligence'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AnomaliesRoute: typeof AnomaliesRoute
  LiveMonitoringRoute: typeof LiveMonitoringRoute
  NetworkMapRoute: typeof NetworkMapRoute
  SensorHealthRoute: typeof SensorHealthRoute
  StationsRoute: typeof StationsRoute
  SystemIntelligenceRoute: typeof SystemIntelligenceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anomalies': {
      id: '/anomalies'
      path: '/anomalies'
      fullPath: '/anomalies'
      preLoaderRoute: typeof AnomaliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-monitoring': {
      id: '/live-monitoring'
      path: '/live-monitoring'
      fullPath: '/live-monitoring'
      preLoaderRoute: typeof LiveMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network-map': {
      id: '/network-map'
      path: '/network-map'
      fullPath: '/network-map'
      preLoaderRoute: typeof NetworkMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sensor-health': {
      id: '/sensor-health'
      path: '/sensor-health'
      fullPath: '/sensor-health'
      preLoaderRoute: typeof SensorHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stations': {
      id: '/stations'
      path: '/stations'
      fullPath: '/stations'
      preLoaderRoute: typeof StationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-intelligence': {
      id: '/system-intelligence'
      path: '/system-intelligence'
      fullPath: '/system-intelligence'
      preLoaderRoute: typeof SystemIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AnomaliesRoute: AnomaliesRoute,
  LiveMonitoringRoute: LiveMonitoringRoute,
  NetworkMapRoute: NetworkMapRoute,
  SensorHealthRoute: SensorHealthRoute,
  StationsRoute: StationsRoute,
  SystemIntelligenceRoute: SystemIntelligenceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
